In [11]:
# Import Statements go here
import numpy as np
import numpy.linalg as npla
from scipy import sparse

def pagerank2(E, return_vector = False, max_iters = 1000, tolerance = 1e-6, m = 0.15):
    nrow,ncol = E.shape
    assert nrow==ncol, 'E must be square'
    assert np.max(E)==1 and np.sum(E)==np.count_nonzero(E), 'E must contain only zeros and ones'

    if type(E) is not sparse.csr_matrix:
       print('Warning, converting input from type', type(E), 'to sparse matrix.')
       E = sparse.csr_matrix(E)
    
    print("E Matrix:", E.todense())
 
    outdegree = np.zeros(nrow)
    for i in range(E.size):
       outdegree[E.indices[i]]+=1
    

    e = np.ones(nrow)
    v = e/sum(e)
    
    print('original v:',v)

    there = np.where(outdegree==0)

    for iteration in range(max_iters):
        print("_v", v)
        oldv = v
        SV = np.sum(v)/nrow

        #
        #EV[np.where(outdegree!=0)] = EV[np.where(outdegree!=0)]/outdegree
        #EV = E@v
        #EV = EV / sum(EV)
 
        
        w = np.zeros(nrow)
        non_dangling = outdegree != 0
        w[non_dangling] = v[non_dangling] / outdegree[non_dangling]
        EV = E @ w
        print("EV", EV)
        
        FV = np.ones(nrow)*np.sum(v[there])
        FV[there] -= v[there]

        FV = FV/(nrow-1)

        MV = (1-m)*(EV+FV) + (m*SV)
        print("MV", MV)

  
        v = MV
        eigval = npla.norm(v)
        v = v / eigval

        if npla.norm(v-oldv) < tolerance:
           break
        print("-------------")

    if npla.norm(v-oldv) < tolerance:
       print('Dominant eigenvalue is %f after %d iterations.\n' % (eigval, iteration+1))
    else:
       print('Did not converge to tolerance %e after %d iterations.\n' % (tolerance, max_iters))

    #assert np.all(v>0) or np.all(v<0), 'Error: eigenvector is not all > 0 or < 0'
    #print('eigenvector:',v)
    #print(npla.norm(v-oldv))
    vector = np.abs(v)
    #print('outdegree:',outdegree)

    ranking = np.argsort(vector)[::-1]
    if return_vector:
      return ranking,vector
    else:
      return ranking  


# test function

E = np.load('PageRankEG1.npy')
r, v = pagerank2(E, return_vector = True, max_iters = 1000, tolerance = 1e-8)
print('r =', r)
print('v =', v)

Warning, converting input from type <class 'numpy.ndarray'> to sparse matrix.
E Matrix: [[0. 0. 1. 1.]
 [1. 0. 0. 0.]
 [1. 1. 0. 1.]
 [1. 1. 0. 0.]]
original v: [0.25 0.25 0.25 0.25]
_v [0.25 0.25 0.25 0.25]
EV [0.375      0.08333333 0.33333333 0.20833333]
MV [0.35625    0.10833333 0.32083333 0.21458333]
-------------
_v [0.66425927 0.20199697 0.5982218  0.40010939]
EV [0.79827649 0.22141976 0.52247294 0.32241824]
MV [0.74845705 0.25812882 0.51402402 0.34397754]
-------------
_v [0.74497878 0.25692923 0.51163523 0.34237899]
EV [0.68282472 0.24832626 0.54798037 0.37679088]
MV [0.6499981  0.28067441 0.5353804  0.38986933]
-------------
_v [0.6704554  0.28950803 0.55223036 0.40213964]
EV [0.75330017 0.22348513 0.56930897 0.36823915]
MV [0.71209265 0.26174987 0.55570013 0.38479078]
-------------
_v [0.70081087 0.25760293 0.54689609 0.37869449]
EV [0.73624334 0.23360362 0.55175233 0.36240509]
MV [0.696457   0.26921324 0.53963965 0.37869449]
-------------
_v [0.69920729 0.27027636 0.54177067